# -*- coding: utf-8 -*-
"""Hello World

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AAd_UHtpwbO0vh58cdPUVxOGR_slapcx
"""

print("Hello World")
print("Hello World\n" *50)